import { ConfigProvider, ConfigProviderProps, Layout } from "antd";
import Sider from "antd/es/layout/Sider";
import { Content } from "antd/es/layout/layout";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RQProvider from "./(providers)/RQProvide";
import { RTProvider } from "./(providers)/RTProvider";
import SidePanel from "./SidePanel";
import "./globals.css";
import { FaRegBell } from "react-icons/fa";
import { IoMdInformationCircleOutline } from "react-icons/io";
import Profile from "./components/profile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getThemeProvider = (): ConfigProviderProps => ({
  direction: "ltr",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RTProvider>
        <RQProvider>
          <body className={inter.className}>
            <ConfigProvider
              {...getThemeProvider()}
              theme={{
                components: {
                  Layout: {
                    bodyBg: "#FCFCFD",
                    colorPrimary: "#9373EE",
                  },
                },
              }}
            >
              <Layout
                className="h-[100vh] "
                style={{ backgroundColor: "#FCFCFD" }}
              >
                <Layout>
                  <Sider
                    style={{ backgroundColor: "#FCFCFD", maxWidth: "300px" }}
                  >
                    <div className="py-2">
                      <img src="Fields.png" />
                    </div>
                    <SidePanel />
                    <Profile
                      userInfo={{
                        name: "Sara Moradi",
                        Email: "Lorem",
                        imageSrc: "image 5.png",
                      }}
                    />
                  </Sider>
                  <Content>{children}</Content>
                </Layout>
              </Layout>
            </ConfigProvider>
          </body>
        </RQProvider>
      </RTProvider>
    </html>
  );
}
